from __future__ import annotations

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication

from core.config import settings


class EmailSender:
    def __init__(self) -> None:
        self.smtp_host = getattr(settings, 'smtp_host', 'smtp.gmail.com')
        # 1. Correção: Garantir que a porta seja um número inteiro
        self.smtp_port = int(getattr(settings, 'smtp_port', 465)) 
        self.smtp_user = getattr(settings, 'smtp_user', '')
        self.smtp_password = getattr(settings, 'smtp_password', '')
        
        # 2. Correção: O remetente TEM que ser o mesmo e-mail usado no SMTP_USER
        self._FROM = f'Teacher Tati <{self.smtp_user}>' 
        
        self._ready = bool(self.smtp_host and self.smtp_user and self.smtp_password)

    def _send(self, to_email: str, subject: str, html: str, attachments: list | None = None) -> bool:
        if not self._ready:
            print(f'[EmailSender] SMTP not configured. Email to {to_email}: {subject}')
            return False

        msg = MIMEMultipart()
        msg['From'] = self._FROM
        msg['To'] = to_email
        msg['Subject'] = subject

        msg.attach(MIMEText(html, 'html'))

        if attachments:
            for file_path in attachments:
                if os.path.exists(file_path):
                    with open(file_path, 'rb') as f:
                        part = MIMEApplication(f.read(), Name=os.path.basename(file_path))
                        part['Content-Disposition'] = f'attachment; filename="{os.path.basename(file_path)}"'
                        msg.attach(part)

        try:
            # 3. Correção: Suporte dual (SSL Implícito vs STARTTLS)
            # Port 465: Requer SMTP_SSL (conexão já nasce criptografada)
            # Port 587: Requer SMTP + STARTTLS (apresentação em texto e depois criptografa)
            
            if self.smtp_port == 465:
                server_class = smtplib.SMTP_SSL
                use_starttls = False
            else:
                server_class = smtplib.SMTP
                use_starttls = True

            with server_class(self.smtp_host, self.smtp_port, timeout=15) as server:
                server.set_debuglevel(0)
                server.ehlo()
                
                if use_starttls and server.has_extn('STARTTLS'):
                    server.starttls()
                    server.ehlo()
                
                server.login(self.smtp_user, self.smtp_password)
                server.send_message(msg)
            return True
        except smtplib.SMTPConnectError:
            print(f'[EmailSender] Connection Failed: Could not connect to {self.smtp_host}:{self.smtp_port}')
            return False
        except smtplib.SMTPAuthenticationError:
            print(f'[EmailSender] Auth Failed: Invalid username or password (check App Password)')
            return False
        except smtplib.SMTPException as smtpe:
            print(f'[EmailSender] SMTP Protocol Error: {smtpe}')
            return False
        except Exception as exc:
            print(f'[EmailSender] Unexpected Error: {exc}')
            return False

    # =====================================================================
    # Seus métodos abaixo continuam inalterados! O "motor" já foi trocado.
    # =====================================================================

    def send_report_email(self, to_email: str, name: str, pdf_path: str, lang: str = 'en-US') -> bool:
        t = {
            'subject': '📊 Your Weekly Progress Report - Teacher Tati AI',
            'title': 'Your Evolution Report is Here!',
            'body': f'Hi <strong>{name}</strong>,<br/><br/>Congratulations on another week of learning! Attached is your detailed progress report generated by Tati AI.',
            'footer': 'Teacher Tati Team'
        }

        html = f"""
<div style="font-family:Arial,sans-serif;max-width:600px;color:#333;">
<h2 style="color:#6366f1;">{t['title']}</h2>
<p>{t['body']}</p>
<p>Review your highlights, completed goals, and learning gaps to keep evolving.</p>
<hr style="border:0;border-top:1px solid #eee;margin:20px 0;">
<p style="font-size:12px;color:#999;">{t['footer']}</p>
</div>
"""
        return self._send(to_email, t['subject'], html, attachments=[pdf_path])

    def send_email(self, fromemail: str, to_email: str, subject: str, html: str) -> bool:
        return self._send(to_email, subject, html)

    def _send_smtp_email(self, fromemail: str, to_email: str, subject: str, html: str) -> bool:
        return self._send(to_email, subject, html)

    def send_reset_email(self, to_email: str, name: str, temp_password: str) -> bool:
        subject = 'Teacher Tati — Your temporary password'
        html = self._build_email_html(name, temp_password)
        return self._send(to_email, subject, html)

    def _build_email_html(self, name: str, temp_password: str) -> str:
        return f"""
<div style="font-family:Arial,sans-serif;max-width:600px;color:#333;">
<h2 style="color:#6366f1;">Your Temporary Password</h2>
<p>Hi <strong>{name}</strong>,</p>
<p>You requested a new password for your Teacher Tati account.</p>
<div style="background:#f3f4f6;padding:20px;text-align:center;border-radius:8px;margin:20px 0;">
<p style="margin:0;font-size:14px;color:#666;">Use the password below to log in:</p>
<p style="margin:10px 0 0;font-size:24px;font-weight:bold;color:#1f2937;">{temp_password}</p>
</div>
<p>We recommend changing your password in your profile settings after logging in.</p>
<p style="color:#ef4444;font-size:13px;">If you didn't request this change, please ignore this email.</p>
<hr style="border:0;border-top:1px solid #eee;margin:20px 0;">
<p style="font-size:12px;color:#999;">Teacher Tati Team</p>
</div>
"""

    def send_submission_notification(self, student_name: str, activity_title: str) -> bool:
        subject = f'New submission: {activity_title}'
        html = f"""
<div style="font-family:Arial,sans-serif;max-width:600px;">
<h2 style="color:#6366f1;">New Activity Submission</h2>
<p>The student <strong>{student_name}</strong> submitted:
<strong>{activity_title}</strong>.</p>
<p>Access the dashboard to review it.</p>
</div>
"""
        admin_email = self.smtp_user or 'admin@seudominio.com'
        return self._send(admin_email, subject, html)

    def send_feedback_notification(
        self, student_name: str, student_email: str, category: str, message: str,
    ) -> bool:
        category_labels = {
            'bug': '🐛 Bug',
            'feature': '💡 Feature Request',
            'feedback': '💬 General Feedback',
            'other': '📝 Other',
        }
        category_label = category_labels.get(category, 'Other')
        subject = f'[{category_label}] Feedback from {student_name}'
        html = f"""
<div style="font-family:Arial,sans-serif;max-width:600px;">
<h2 style="color:#6366f1;">New Feedback Received</h2>
<p><strong>User:</strong> {student_name}</p>
<p><strong>Email:</strong> {student_email}</p>
<p><strong>Category:</strong> {category_label}</p>
<p><strong>Message:</strong><br>{message.replace(chr(10), '<br>')}</p>
</div>
"""
        admin_email = self.smtp_user or 'admin@seudominio.com'
        return self._send(admin_email, subject, html)

    def send_correction_notification(
        self, student_name: str, student_email: str, activity_title: str, score: int, feedback: str,
    ) -> bool:
        subject = f'Activity Graded: {activity_title}'

        if score >= 90:
            score_message = 'Excellent work! 🎉'
        elif score >= 70:
            score_message = 'Great job! 👍'
        elif score >= 50:
            score_message = 'Keep practicing! 📚'
        else:
            score_message = "Let's study a bit more! 💪"

        html = f"""
<div style="font-family:Arial,sans-serif;max-width:600px;">
<h2 style="color:#6366f1;">Activity Graded</h2>
<p>Hello, <strong>{student_name}</strong>!</p>
<p>Your activity <strong>"{activity_title}"</strong> has been reviewed.</p>
<div style="background:#f3f4f6;border-radius:8px;padding:1rem;margin:1rem 0;">
<p style="margin:0;color:#666;">Your score:</p>
<p style="margin:0;font-size:2rem;font-weight:700;color:#6366f1;">{score}/100</p>
<p style="margin:0.5rem 0 0;color:#4ade80;">{score_message}</p>
</div>
<div style="background:hsla(258,80%,58%,0.05);border:1px solid #6366f1;border-radius:8px;padding:1rem;">
<p style="margin:0 0 0.5rem;font-weight:600;color:#6366f1;">Teacher's Feedback:</p>
<p style="margin:0;line-height:1.6;">{feedback.replace(chr(10), '<br>')}</p>
</div>
<p style="margin-top:1.5rem;color:#666;font-size:0.9rem;">Keep up the good work and stay focused!</p>
</div>
"""
        return self._send(student_email, subject, html)

    def send_streak_email(
        self, to_email: str, name: str, streak_days: int, mode: str = 'reminder'
    ) -> bool:
        if mode == 'broken':
            subject = '⚠️ Your streak was broken — Teacher Tati'
            body_html = f"""
<p>Hi <strong>{name}</strong>,</p>
<p>Your streak of <strong>{streak_days} days</strong> was broken. 😔</p>
<p>Don't give up! Come back today and start a new streak.</p>
<a href="https://tati-ai.vercel.app/chat"
style="display:inline-block;background:#6366f1;color:#fff;padding:0.6rem 1.4rem;
border-radius:8px;text-decoration:none;margin-top:1rem;">
Practice Now 🚀
</a>
"""
        else:
            subject = '🔥 Keep your streak alive — Teacher Tati'
            body_html = f"""
<p>Hi <strong>{name}</strong>,</p>
<p>You are on a <strong>{streak_days}-day streak</strong>! 🔥</p>
<p>Don't lose it — practice a little today to keep the momentum going.</p>
<a href="https://tati-ai.vercel.app/chat"
style="display:inline-block;background:#6366f1;color:#fff;padding:0.6rem 1.4rem;
border-radius:8px;text-decoration:none;margin-top:1rem;">
Keep Practicing 💪
</a>
"""

        html = f"""
<div style="font-family:Arial,sans-serif;max-width:600px;">
<h2 style="color:#6366f1;">{'Streak Broken!' if mode == 'broken' else 'Daily Reminder'}</h2>
{body_html}
<hr style="border:0;border-top:1px solid #eee;margin:20px 0;">
<p style="font-size:12px;color:#999;">Teacher Tati Team</p>
</div>
"""
        return self._send(to_email, subject, html)

    def send_trophy_email(
        self, to_email: str, name: str, trophy_name: str, trophy_icon: str = '🏆'
    ) -> bool:
        subject = f'🏆 New trophy unlocked: {trophy_name} — Teacher Tati'
        html = f"""
<div style="font-family:Arial,sans-serif;max-width:600px;text-align:center;">
<h2 style="color:#6366f1;">New Trophy Unlocked!</h2>
<div style="font-size:4rem;margin:1.5rem 0;">{trophy_icon}</div>
<h3 style="color:#1f2937;">{trophy_name}</h3>
<p>Congratulations, <strong>{name}</strong>! You earned a new trophy.</p>
<a href="https://tati-ai.vercel.app/activities"
style="display:inline-block;background:#6366f1;color:#fff;padding:0.6rem 1.4rem;
border-radius:8px;text-decoration:none;margin-top:1rem;">
View My Trophies 🏆
</a>
<hr style="border:0;border-top:1px solid #eee;margin:20px 0;">
<p style="font-size:12px;color:#999;">Teacher Tati Team</p>
</div>
"""
        return self._send(to_email, subject, html)

    def send_new_activity_email(
        self, to_email: str, name: str, activity_title: str, activity_url: str = 'https://tati-ai.vercel.app/activities',
    ) -> bool:
        subject = f'📚 New activity available: {activity_title} — Teacher Tati'
        html = f"""
<div style="font-family:Arial,sans-serif;max-width:600px;">
<h2 style="color:#6366f1;">New Activity Available! 📚</h2>
<p>Hi <strong>{name}</strong>,</p>
<p>Teacher Tati published a new activity for you:
<strong>{activity_title}</strong>.</p>
<a href="{activity_url}"
style="display:inline-block;background:#6366f1;color:#fff;padding:0.6rem 1.4rem;
border-radius:8px;text-decoration:none;margin-top:1rem;">
Start Activity →
</a>
<hr style="border:0;border-top:1px solid #eee;margin:20px 0;">
<p style="font-size:12px;color:#999;">Teacher Tati Team</p>
</div>
"""
        return self._send(to_email, subject, html)