from __future__ import annotations
import json
from services.llm import groq_chat
from services.database import get_client

PERSONALIZED_MODULE_ID = '00000000-0000-0000-0000-000000000001'

async def generate_exercises_from_history(username: str, current_conversations_text: str, exercise_type: str = 'quiz') -> str | None:
    db = get_client()

    # busca até 15 conversas mais recentes do aluno
    all_context = current_conversations_text
    try:
        past_convs = (
            db.table('conversations')
            .select('id')
            .eq('username', username)
            .order('updated_at', desc=True)
            .limit(15)
            .execute()
        )

        for c in past_convs.data:
            msgs = (
                db.table("messages")
                .select("content, role")
                .eq("session_id", c["id"])
                .order("created_at")
                .limit(40) # limita por conversa
                .execute()
            )

            all_context += "\n\n" + "\n".join(
                f"{m['role'].upper()}: {m['content']}" for m in msgs.data
            )
    except Exception as e:
        print(f"[ExerciseGen] Aviso ao buscar histórico: {e}")

    # Prompts por tipo
    type_prompts = {
        "quiz": (
            "Generate 5 multiple-choice questions targeting the student's specific mistakes.\n"
            "Return JSON: {\"title\": \"...\", \"description\": \"...\", \"exercises\": "
            "[{\"question\": \"...\", \"options\": [\"A\",\"B\",\"C\",\"D\"], \"correct_index\": 0, \"explanation\": \"...\"}]}"
        ),
        "story": (
            "Write a SHORT story (5-8 sentences) in English that naturally uses the grammar structures "
            "the student is struggling with. Then create 3 comprehension questions about the story.\n"
            "Return JSON: {\"title\": \"Story Practice\", \"description\": \"Read and answer\", \"story\": \"...\", "
            "\"exercises\": [{\"question\": \"...\", \"options\": [\"A\",\"B\",\"C\",\"D\"], \"correct_index\": 0, \"explanation\": \"...\"}]}"
        ),
        "fill_in": (
            "Create 5 fill-in-the-blank sentences targeting the student's grammar mistakes. "
            "Each sentence has exactly one blank. Provide 4 options where only one is correct.\n"
            "Return JSON: {\"title\": \"Fill in the Blanks\", \"description\": \"Choose the correct word\", "
            "\"exercises\": [{\"question\": \"She ___ to school every day. (go/goes/going/went)\", "
            "\"options\": [\"go\",\"goes\",\"going\",\"went\"], \"correct_index\": 1, \"explanation\": \"...\"}]}"
        ),
        "dialogue": (
            "Write a short dialogue (6-8 lines) between two people that demonstrates correct usage of "
            "the grammar the student keeps getting wrong. Then create 3 questions about the dialogue.\n"
            "Return JSON: {\"title\": \"Dialogue Practice\", \"description\": \"Read and answer\", \"dialogue\": \"...\", "
            "\"exercises\": [{\"question\": \"...\", \"options\": [\"A\",\"B\",\"C\",\"D\"], \"correct_index\": 0, \"explanation\": \"...\"}]}"
        ),
    }

    type_titles = {
        "quiz": "Personalized Quiz",
        "story": "Story Practice",
        "fill_in": "Fill in the Blanks",
        "dialogue": "Dialogue Practice",
    }

    prompt = (
        f"You are an expert English teacher. Analyze these student conversations and identify their REAL recurring mistakes.\n\n"
        f"Student conversations:\n{all_context[:6000]}\n\n"
        f"Based on the mistakes found:\n{type_prompts.get(exercise_type, type_prompts['quiz'])}\n\n"
        "Return ONLY valid JSON, no markdown, no extra text."
    )

    try:
        res = await groq_chat(
            messages=[{"role": "user", "content": prompt}],
            max_tokens=1500,
            temperature=0.6,
        )

        start = res.find("{")
        end = res.rfind("}") + 1
        if start == -1 or end == 0:
            raise ValueError("JSON não encontrado na resposta")
        data = json.loads(res[start:end])

        # garante que o módulo mestre existe
        try:
            mod_check = db.table("modules").select("id").eq("id", PERSONALIZED_MODULE_ID).execute()
            if not mod_check.data:
                db.table("modules").insert({
                    "id": PERSONALIZED_MODULE_ID,
                    "title": "Personalized Practice",
                    "description": "Exercises generated by Tati based on your chat history.",
                    "level": "All",
                    "is_published": True,
                }).execute()
        except Exception as e:
            print(f"[ExerciseGen] Aviso módulo: {e}")

        # Cria o Quiz vinculado ao username
        quiz_res = db.table("quizzes").insert({
            "module_id": PERSONALIZED_MODULE_ID,
            "username": username,
            "title": data.get("title", type_titles.get(exercise_type, "Personalized Practice")),
            "description": data.get("description", "Based on your recent mistakes."),
        }).execute()

        if not quiz_res.data:
            return None

        quiz_id = quiz_res.data[0]["id"]

        # Insere as questões
        for i, q in enumerate(data.get("exercises", [])):
            db.table("quiz_questions").insert({
                "quiz_id": quiz_id,
                "question": q.get("question", ""),
                "options": q.get("options", []),
                "correct_index": q.get("correct_index", 0),
                "explanation": q.get("explanation", ""),
                "order": i,
            }).execute()

        # Invalida cache para o aluno ver o novo quiz imediatamente
        try:
            from services.upstash import cache_delete
            await cache_delete(f"modules:list:{username}")
        except:
            pass

        print(f"[ExerciseGen] Quiz gerado com sucesso: {quiz_id} para {username}")
        return quiz_id

    except Exception as e:
        print(f"[ExerciseGen] Erro: {e}")
        return None