'use client';

import { useState } from 'react';

import { cn } from '@/lib/utils';
import { FileText, Languages, Clock } from 'lucide-react';

interface TranscriptSegment {
  start: string;
  source_text: string;
  translated_text: string;
}

interface TranscriptPanelProps {
  segments: TranscriptSegment[];
  onPhraseClick?: (text: string) => void;
}

export function TranscriptPanel({ segments, onPhraseClick }: TranscriptPanelProps) {

  const [mode, setMode] = useState<'source' | 'translated'>('source');

  if (!segments || segments.length === 0) return null;

  return (
    <div className="bg-surface border border-border rounded-2xl overflow-hidden flex flex-col h-full shadow-sm">
      <div className="p-4 border-b border-border bg-bg-secondary/50 flex items-center justify-between gap-4">
        <h3 className="text-sm font-bold text-text flex items-center gap-2">
          <FileText size={18} className="text-primary" />
          {'Guided transcript'}
        </h3>

        <div className="flex bg-bg border border-border rounded-lg p-0.5">
          <button
            onClick={() => setMode('source')}
            className={cn(
              "px-3 py-1.5 rounded-md text-[0.65rem] font-bold uppercase tracking-wider transition-all",
              mode === 'source' ? "bg-primary text-white shadow-sm" : "text-text-muted hover:text-text"
            )}
          >
            {'Original'}
          </button>
          <button
            onClick={() => setMode('translated')}
            className={cn(
              "px-3 py-1.5 rounded-md text-[0.65rem] font-bold uppercase tracking-wider transition-all",
              mode === 'translated' ? "bg-primary text-white shadow-sm" : "text-text-muted hover:text-text"
            )}
          >
            {'Translation'}
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-4 max-h-[500px] scrollbar-thin">
        {segments.map((segment, idx) => (
          <div
            key={idx}
            className={cn(
              "flex gap-4 group transition-all duration-200 p-2 rounded-xl border border-transparent",
              onPhraseClick && "cursor-pointer hover:bg-primary/5 hover:border-primary/10 active:scale-[0.98]"
            )}
            onClick={() => onPhraseClick?.(segment.source_text)}
          >
            <div className="shrink-0 pt-1">
              <span className="flex items-center gap-1 text-[0.65rem] font-mono font-bold text-text-subtle bg-bg-secondary px-1.5 py-0.5 rounded border border-border group-hover:border-primary/30 transition-colors">
                <Clock size={10} />
                {segment.start}
              </span>
            </div>
            <div className="flex-1 space-y-1">
              <p className={cn(
                "text-sm leading-relaxed transition-colors",
                mode === 'source' ? "text-text font-medium" : "text-text-muted"
              )}>
                {mode === 'source' ? segment.source_text : segment.translated_text}
              </p>
              {mode === 'translated' && segment.source_text && (
                <p className="text-[0.7rem] text-text-subtle italic">
                  {segment.source_text}
                </p>
              )}
            </div>
          </div>
        ))}
      </div>

      <div className="p-3 border-t border-border bg-bg-secondary/30">
        <p className="text-[0.65rem] text-text-subtle flex items-center gap-1.5">
          <Languages size={12} />
          {'Translation automatically generated by AI.'}
        </p>
      </div>
    </div>
  );
}
