FROM python:3.12-slim

# Instala os pacotes pesados necessários para manipulação de arquivos e PDFs
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libreoffice \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir pip==24.2 \
    && pip install --no-cache-dir -r requirements.txt

COPY . .

# Inicializa o processo do Celery Worker ouvindo a fila e processando o Cron (Beat)
CMD ["celery", "-A", "app.core.celery_app", "worker", "--beat", "--loglevel=info", "--concurrency=2", "--without-gossip", "--without-mingle", "--without-heartbeat"]
