from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
import pathlib

router = APIRouter()

@router.get('/exercises/pdf')
async def get_exercises_pdf():
    """Serve the generated exercises PDF.
    The PDF is generated by the `generate_exercises_pdf.py` script and placed
    in the brain artifacts directory.
    """
    pdf_path = pathlib.Path(__file__).resolve().parents[3] / 'exercises.pdf'
    if not pdf_path.is_file():
        raise HTTPException(status_code=404, detail='PDF not found. Generate it first.')
    return FileResponse(path=pdf_path, media_type='application/pdf', filename='exercises.pdf')
