# Generated by Django 6.0.8 on 2026-08-26 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(db_column='username', max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', default='', max_length=255)),
                ('email', models.CharField(blank=True, db_column='email', max_length=255, null=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('role', models.CharField(db_column='role', default='student', max_length=50)),
                ('level', models.CharField(blank=True, db_column='level', default='A1', max_length=20, null=True)),
                ('profile', models.JSONField(blank=True, db_column='profile', default=dict, null=True)),
                ('streak_data', models.JSONField(blank=True, db_column='streak_data', default=dict, null=True)),
                ('xp_data', models.JSONField(blank=True, db_column='xp_data', default=dict, null=True)),
                ('study_goals', models.JSONField(blank=True, db_column='study_goals', default=list, null=True)),
                ('vocabulary', models.JSONField(blank=True, db_column='vocabulary', default=dict, null=True)),
                ('weekly_plan', models.JSONField(blank=True, db_column='weekly_plan', default=dict, null=True)),
                ('temp_password', models.CharField(blank=True, db_column='temp_password', max_length=255, null=True)),
                ('is_exempt', models.BooleanField(blank=True, db_column='is_exempt', default=False, null=True)),
                ('is_premium_active', models.BooleanField(blank=True, db_column='is_premium_active', default=False, null=True)),
                ('plan_type', models.CharField(blank=True, db_column='plan_type', max_length=50, null=True)),
                ('created_at', models.CharField(db_column='created_at', default=django.utils.timezone.now, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', null=True)),
            ],
            options={
                'verbose_name': 'Usuário Supabase',
                'verbose_name_plural': 'Usuários Supabase',
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
