"""
services/progress_report.py
Gera relatórios de evolução pedagógica em PDF para os alunos.
"""

import os
from datetime import datetime, timedelta, timezone
from typing import Dict, Any, List
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from app.core.database import get_client
from fastapi.concurrency import run_in_threadpool

class ProgressReportService:
    def __init__(self):
        self.db = get_client()

    async def generate_student_report(self, username: str, lang: str = 'en-US') -> str:
        """
        Gera um PDF com o progresso semanal do aluno (Exclusivamente em Inglês).
        """
        t = {
            'title': 'Weekly Evolution Report',
            'period': 'Period: Last 7 days',
            'level': 'Level:',
            'highlights': 'Weekly Highlights',
            'msgs': 'Messages Sent',
            'errors': 'Errors Captured',
            'plan_status': 'Plan Status',
            'active': 'Active',
            'none': 'Inactive',
            'goals': 'Weekly Goals Progress',
            'gaps': 'Learning Gaps & Corrections',
            'mistake': 'You said',
            'correction': 'Tati recommends',
            'footer_1': 'Keep practicing! Consistency is the key to fluency.',
            'footer_2': 'Automatically generated by Teacher Tati AI.'
        }

        # 1. Coleta dados da semana
        seven_days_ago = (datetime.now(timezone.utc) - timedelta(days=7)).isoformat()
        
        def _fetch_data():
            user = self.db.table('users').select('name, weekly_plan, level').eq('username', username).single().execute().data
            if not user: return None
            
            msgs = self.db.table('messages').select('id').eq('username', username).eq('role', 'user').gte('created_at', seven_days_ago).execute().data
            errors = self.db.table('user_errors').select('*').eq('username', username).gte('created_at', seven_days_ago).execute().data
            return {"messages_count": len(msgs), "user": user, "errors": errors}

        data = await run_in_threadpool(_fetch_data)
        if not data: return ""
        
        user_info = data['user']
        
        # 2. Cria o PDF
        report_dir = "backend/assets/reports"
        os.makedirs(report_dir, exist_ok=True)
        filename = f"{report_dir}/report_{username}_{datetime.now().strftime('%Y%m%d')}.pdf"
        
        doc = SimpleDocTemplate(filename, pagesize=A4, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
        styles = getSampleStyleSheet()
        story = []

        # Cores da Marca
        BRAND_PURPLE = colors.HexColor("#6C63FF")
        BRAND_BG = colors.HexColor("#F8F7FF")
        TEXT_DARK = colors.HexColor("#1A1A2E")
        TEXT_MUTED = colors.HexColor("#6B7280")

        # Estilos Customizados
        title_style = ParagraphStyle('TitleStyle', parent=styles['Heading1'], textColor=BRAND_PURPLE, fontSize=26, fontName='Helvetica-Bold', spaceAfter=5)
        period_style = ParagraphStyle('PeriodStyle', parent=styles['Normal'], textColor=TEXT_MUTED, fontSize=10, spaceAfter=30)
        section_style = ParagraphStyle('SectionStyle', parent=styles['Heading2'], textColor=TEXT_DARK, fontSize=16, fontName='Helvetica-Bold', spaceBefore=20, spaceAfter=15, borderPadding=5)
        card_style = ParagraphStyle('CardStyle', parent=styles['Normal'], fontSize=11, leading=14)

        # Cabeçalho Profissional
        story.append(Paragraph(t['title'], title_style))
        story.append(Paragraph(f"Student: <b>{user_info.get('name', username)}</b> | {t['level']} <b>{user_info.get('level', 'N/A')}</b>", card_style))
        story.append(Paragraph(t['period'], period_style))

        # --- Dashboard Box (Highlights) ---
        story.append(Paragraph(t['highlights'], section_style))
        stats_data = [
            [Paragraph(f"<b>{data['messages_count']}</b><br/><font color='#6B7280' size='8'>{t['msgs']}</font>", card_style),
             Paragraph(f"<b>{len(data['errors'])}</b><br/><font color='#6B7280' size='8'>{t['errors']}</font>", card_style),
             Paragraph(f"<b>{t['active'] if user_info.get('weekly_plan') else t['none']}</b><br/><font color='#6B7280' size='8'>{t['plan_status']}</font>", card_style)]
        ]
        
        st = Table(stats_data, colWidths=[160, 160, 160])
        st.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), BRAND_BG),
            ('ROUNDEDCORNERS', [12, 12, 12, 12]),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 15),
            ('TOPPADDING', (0, 0), (-1, -1), 15),
            ('LINEBELOW', (0, 0), (-1, -1), 0, colors.white), # Esconde linhas
        ]))
        story.append(st)
        story.append(Spacer(1, 25))

        # --- Weekly Plan Progress ---
        plan = user_info.get('weekly_plan', {})
        if plan and plan.get('topics'):
            story.append(Paragraph(t['goals'], section_style))
            plan_data = []
            for topic in plan['topics']:
                status = "✅" if topic.get('status') == 'completed' else "⏳"
                plan_data.append([
                    Paragraph(status, card_style),
                    Paragraph(f"<b>{topic.get('title')}</b><br/><font size='8' color='#6B7280'>{topic.get('description', '')}</font>", card_style)
                ])
            
            pt = Table(plan_data, colWidths=[30, 450])
            pt.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ]))
            story.append(pt)
            story.append(Spacer(1, 20))

        # --- Corrections (The pedagogical value) ---
        if data['errors']:
            story.append(Paragraph(t['gaps'], section_style))
            err_table_data = [[Paragraph(f"<b>{t['mistake']}</b>", card_style), Paragraph(f"<b>{t['correction']}</b>", card_style)]]
            
            for err in data['errors'][:15]: # Mostra mais erros no PDF novo
                err_table_data.append([
                    Paragraph(f"<font color='#EF4444'><s>{err.get('incorrect_text', '')}</s></font>", card_style),
                    Paragraph(f"<font color='#10B981'><b>{err.get('correct_text', '')}</b></font><br/><font size='8' color='#6B7280'><i>{err.get('explanation', '')}</i></font>", card_style)
                ])
            
            et = Table(err_table_data, colWidths=[200, 280])
            et.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), BRAND_PURPLE),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ]))
            story.append(et)

        # Rodapé Elegante
        story.append(Spacer(1, 60))
        story.append(Paragraph(f"<center>{t['footer_1']}</center>", styles['Italic']))
        story.append(Spacer(1, 10))
        story.append(Paragraph(f"<center><font color='#6B7280' size='8'>{t['footer_2']}</font></center>", styles['Normal']))

        doc.build(story)
        return filename


def get_weekly_report(username: str) -> dict:
    """Retorna dados de progresso semanal para o dashboard."""
    from app.core.database import get_client
    db = get_client()
    now = datetime.now(timezone.utc)
    week_ago = now - timedelta(days=7)

    # Busca mensagens da semana
    messages = db.table('messages').select('created_at, session_id').eq('username', username).eq('role', 'user').gte('created_at', week_ago.isoformat()).execute().data or []

    # Busca sessões (para study_days)
    sessions = db.table('study_sessions').select('created_at').eq('username', username).gte('created_at', week_ago.isoformat()).execute().data or []

    # Processa mensagens por dia (últimos 7 dias)
    days = [(now - timedelta(days=i)).strftime('%a') for i in range(6, -1, -1)]
    msg_counts = [0] * 7
    session_ids = set()
    study_days = set()

    for m in messages:
        created = m.get('created_at', '')
        if not created:
            continue
        try:
            dt = datetime.fromisoformat(created.replace('Z', '+00:00'))
            delta_days = (dt.date() - week_ago.date()).days - 1
            if 0 <= delta_days < 7:
                msg_counts[delta_days] += 1
            study_days.add(dt.date())
            if m.get('session_id'):
                session_ids.add(m['session_id'])
        except Exception:
            pass

    # Também conta dias das sessões de estudo
    for s in sessions:
        created = s.get('created_at', '')
        if created:
            try:
                dt = datetime.fromisoformat(created.replace('Z', '+00:00'))
                study_days.add(dt.date())
            except Exception:
                pass

    return {
        'period': 'weekly',
        'total_conversations': len(session_ids),
        'total_messages': len(messages),
        'study_days': len(study_days),
        'unique_words_used': 0,
        'current_streak': 0,
        'messages_by_day': msg_counts,
        'days_of_week': days,
    }


def get_monthly_report(username: str) -> dict:
    """Retorna dados de progresso mensal para o dashboard."""
    from app.core.database import get_client
    db = get_client()
    now = datetime.now(timezone.utc)

    # Início do mês atual
    month_start = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0)

    # Busca mensagens do mês
    messages = (
        db.table('messages')
        .select('created_at, session_id')
        .eq('username', username)
        .eq('role', 'user')
        .gte('created_at', month_start.isoformat())
        .execute()
        .data or []
    )

    # Busca sessões do mês
    sessions = (
        db.table('study_sessions')
        .select('created_at')
        .eq('username', username)
        .gte('created_at', month_start.isoformat())
        .execute()
        .data or []
    )

    # Agrupa mensagens por semana (4 semanas do mês)
    messages_by_week = [0, 0, 0, 0]
    study_days = set()
    session_ids = set()

    for m in messages:
        created = m.get('created_at', '')
        if not created:
            continue
        try:
            dt = datetime.fromisoformat(created.replace('Z', '+00:00'))
            week_idx = min((dt.day - 1) // 7, 3)
            messages_by_week[week_idx] += 1
            study_days.add(dt.date())
            if m.get('session_id'):
                session_ids.add(m['session_id'])
        except Exception:
            pass

    # Também conta dias de sessões de estudo
    for s in sessions:
        created = s.get('created_at', '')
        if created:
            try:
                dt = datetime.fromisoformat(created.replace('Z', '+00:00'))
                study_days.add(dt.date())
            except Exception:
                pass

    return {
        'period': 'monthly',
        'total_conversations': len(session_ids),
        'total_messages': len(messages),
        'study_days': len(study_days),
        'unique_words_used': 0,
        'current_streak': 0,
        'longest_streak': 0,
        'messages_by_week': messages_by_week,
    }


progress_report_service = ProgressReportService()
