# Generated by Django 6.0.8 on 2026-08-26 12:19

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivitySubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=150)),
                ("module_id", models.UUIDField(blank=True, null=True)),
                ("activity_type", models.CharField(max_length=50)),
                ("student_answer", models.TextField(blank=True, default="")),
                ("teacher_feedback", models.TextField(blank=True, default="")),
                ("ai_feedback", models.TextField(blank=True, default="")),
                ("score", models.IntegerField(default=100)),
                ("status", models.CharField(default="completed", max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "activity_submissions",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CEFRReference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("storage_url", models.URLField(max_length=1000)),
                ("cefr_level", models.CharField(default="A1", max_length=20)),
                ("file_type", models.CharField(default="pdf", max_length=50)),
                ("file_size", models.BigIntegerField(default=0)),
                ("chunks_indexed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "cefr_references",
                "ordering": ["cefr_level", "filename"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CEFRSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("weekdays", models.JSONField(blank=True, default=list, null=True)),
                ("execution_time", models.TimeField(blank=True, null=True)),
                ("weekly_frequency", models.IntegerField(default=1)),
                ("materials_per_execution", models.IntegerField(default=5)),
                (
                    "selected_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "cefr_schedules",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("level", models.CharField(default="A1", max_length=20)),
                ("front", models.TextField()),
                ("back", models.TextField()),
                ("explanation", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("topic", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "cefr_flashcards",
                "ordering": ["level", "front"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("wordwall_url", models.URLField(max_length=1000)),
                (
                    "levels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        null=True,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "games",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("level", models.CharField(default="all", max_length=20)),
                ("order", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("flashcards", models.JSONField(blank=True, default=list, null=True)),
                ("levels", models.JSONField(blank=True, default=list, null=True)),
                ("image_url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "youtube_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "spotify_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "modules",
                "ordering": ["order", "-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=1000)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "levels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        null=True,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "news",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("level", models.CharField(default="Beginner", max_length=50)),
                ("thumbnail", models.URLField(blank=True, max_length=1000, null=True)),
                ("embed_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("duration", models.CharField(blank=True, default="", max_length=50)),
                (
                    "category",
                    models.CharField(blank=True, default="General", max_length=100),
                ),
                (
                    "source_name",
                    models.CharField(blank=True, default="YouTube", max_length=100),
                ),
                (
                    "source_type",
                    models.CharField(blank=True, default="youtube", max_length=50),
                ),
                (
                    "media_type",
                    models.CharField(blank=True, default="video", max_length=50),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "transcript_segments",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("has_full_transcript", models.BooleanField(default=False)),
                ("theme_tags", models.JSONField(blank=True, default=list, null=True)),
                ("easy_words", models.JSONField(blank=True, default=list, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "podcasts",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PremiumContent",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("type", models.CharField(default="book", max_length=50)),
                (
                    "content_source",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("emoji", models.CharField(default="📚", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("category", models.CharField(default="materials", max_length=100)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_secure", models.BooleanField(default=True)),
                (
                    "preview_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "processing_status",
                    models.CharField(default="completed", max_length=50),
                ),
                (
                    "external_links",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "price_students",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "price_buyers",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "premium_content",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Trophy",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("icon", models.CharField(default="🏆", max_length=100)),
                ("category", models.CharField(default="general", max_length=100)),
                (
                    "requirement_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("requirement_value", models.IntegerField(default=1)),
                (
                    "requirement_text",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "trophies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserFlashcardProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=150)),
                ("flashcard_id", models.CharField(max_length=255)),
                ("status", models.CharField(default="correct", max_length=50)),
                ("next_review_date", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "user_flashcard_progress",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserTrophy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=150)),
                ("trophy_id", models.CharField(max_length=100)),
                ("unlocked_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "user_trophies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserVocabulary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=150)),
                ("word", models.CharField(max_length=255)),
                ("definition", models.TextField(blank=True, default="")),
                ("example_sentence", models.TextField(blank=True, default="")),
                ("easiness_factor", models.FloatField(default=2.5)),
                ("interval", models.IntegerField(default=1)),
                ("repetitions", models.IntegerField(default=0)),
                ("next_review", models.DateTimeField(blank=True, null=True)),
                ("last_score", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "user_vocabulary",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
    ]
