# Generated by Django 6.0.8 on 2026-08-26 12:19

import django.contrib.postgres.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEFRSimulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(default='A1', max_length=20)),
                ('topic', models.CharField(max_length=255)),
                ('scenario', models.TextField(blank=True, default='')),
                ('roles', models.JSONField(blank=True, default=dict, null=True)),
                ('goal', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'cefr_simulations',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('title', models.CharField(default='Nova Conversa com a Teacher Tati', max_length=255)),
                ('model', models.CharField(default='groq/llama-3.3-70b-versatile', max_length=100)),
                ('is_simulation', models.BooleanField(blank=True, default=False, null=True)),
                ('simulation_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.CharField(default=django.utils.timezone.now, max_length=100)),
                ('updated_at', models.CharField(default=django.utils.timezone.now, max_length=100)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('role', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('audio_b64', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.CharField(default='all', max_length=50)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True)),
                ('initial_message', models.TextField(blank=True, null=True)),
                ('initial_message_en', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('greeting', models.TextField(blank=True, null=True)),
                ('emoji', models.CharField(default='🎭', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'simulations',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
